# This Workflow runs the checks to verify the code quality
# The current checks are: pylint

# Refer to: https://interstage.atlassian.net/wiki/spaces/TECH/pages/456032266/Code+Quality+Check+In+CI

name: CI - Run Code Quality Check

# Controls when the workflow will run
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quality-check:
    name: Check Code Quality
    needs: run_or_skip_workflow
    if: ${{ needs.run_or_skip_workflow.outputs.run_workflow_flag == 'true' }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - name: Install NPM
        working-directory: ./interstage_project/frontend
        run: npm ci --force

      - name: Get changed .js files
        id: changed-js-files
        uses: tj-actions/changed-files@v23.1
        with:
          separator: " "
          diff_relative: true
          # Only JS files will be included
          files: |
            **/**.js
          # Only the files inside the path interstage_project will be included
          path: "./interstage_project/frontend"

      - name: Run Prettier on changed files
        if: steps.changed-js-files.outputs.any_changed == 'true'
        working-directory: ./interstage_project/frontend
        run: |
          npx prettier --check ${{ steps.changed-js-files.outputs.all_changed_files }}

      - name: Run Lint on changed files
        if: steps.changed-js-files.outputs.any_changed == 'true'
        working-directory: ./interstage_project/frontend
        run: |
          npx eslint ${{ steps.changed-js-files.outputs.all_changed_files }} --no-fix --max-warnings 0

      - name: Run Prettier across all files
        if: always()
        working-directory: ./interstage_project/frontend
        run: |
          npm run pretty:check

      - name: Run EsLint across all files
        if: always()
        working-directory: ./interstage_project/frontend
        run: |
          npx eslint src/ --no-fix --max-warnings 0
